repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/prettier/prettier
    rev: '2.0.5'
    hooks:
      - id: prettier
        name: prettier
        args: ['--write']
        files: "src/frontend/src/"
        language_version: 14.15.0

