version: "3"

services:
  expungeservice:
    build:
      context: src/backend
    image: recordsponge/expungeservice:dev
    volumes:
      - ./src/backend:/src/backend
      - ./src/frontend:/src/frontend
    ports:
      - "5000:5000"

  node:
    command: sh -c "cd /src/frontend && npm install && npm start"
    depends_on:
      - expungeservice
    image: node:13.13.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/src/frontend
      - node_modules:/src/frontend/node_modules

volumes:
  node_modules:
