name: recordexpungPDX tests

on: [pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    container:
      image: node:13.13.0-alpine
      env:
        CI: true
    steps:
      - uses: actions/checkout@v2
      - name: run frontend tests
        run: cd src/frontend && npm i && npm run-script ci-test

  backend:
    runs-on: ubuntu-latest
    container:
      image: recordsponge/expungeservice:dev

    steps:
      - uses: actions/checkout@v2
      - name: copy to pipenv project dir
        run: cp -R src/backend/* /src/backend && ls -l /src/backend
      - name: run backend tests
        run: cd /src/backend && pipenv run mypy && pipenv run pytest --cov=expungeservice
