name: deploy to staging

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    container:
      image: node:13.13.0-alpine
      env:
        CI: false
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache make docker rsync openssh git
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa-bastion
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host recordsponge
                User github
                Hostname recordsponge.com
                IdentityFile ~/.ssh/id_rsa-bastion
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build frontend
        run: cd src/frontend && npm i && npm run build
      - name: Deploy to staging
        run: |
          cd src/ops
          make rsync version image RS_ENV=staging
          make push RS_ENV=staging
          make ssh_deploy RS_ENV=staging

